#!/usr/bin/env bash

scripts_folder="$HOME/.local/scripts"

mkdir -p "$scripts_folder"
mkdir -p $HOME/.zsh/
mkdir -p $HOME/.local/bin

zsh_syntax_highlighting="$HOME/.zsh/zsh-syntax-highlighting"
if [[ ! -d "$zsh_syntax_highlighting" ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$zsh_syntax_highlighting"
fi

zsh_autosuggestions="$HOME/.zsh/zsh-autosuggestions"
if [[ ! -d "$zsh_autosuggestions" ]]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions "$zsh_autosuggestions"
fi

backup_folder="$HOME/.backup_dotfiles_$(date +%Y%m%d_%H:%M:%S)"
mkdir -p "$backup_folder"

zshrc="$HOME/.zshrc"
if [[ -f "$zshrc" ]]; then
  mv "$zshrc" "$backup_folder"
fi
cp "$PWD/zshrc" "$zshrc"

if [[ "$(uname)" == "Darwin" ]]; then
  cat "$PWD/zshrc-macos" >>"$zshrc"
else
  cat "$PWD/zshrc-linux" >>"$zshrc"
fi

if [[ "$(uname)" == "Darwin" ]]; then
  ghostty_folder="$HOME/Library/Application Support/com.mitchellh.ghostty"
  mkdir -p "$ghostty_folder"
  ghostty="$ghostty_folder/config.ghostty"
  if [[ -f "$ghostty" ]]; then
    mv "$ghostty" "$backup_folder"
  fi
  cp "$PWD/ghostty" "$ghostty"
fi

tmux="$HOME/.tmux.conf"
if [[ -f "$tmux" ]]; then
  mv "$tmux" "$backup_folder"
fi
cp "$PWD/tmux.conf" "$tmux"

if [[ "$(uname)" == "Darwin" ]]; then
  cat "$PWD/tmux-macos.conf" >>"$tmux"
else
  cat "$PWD/tmux-linux.conf" >>"$tmux"
fi

chmod u+x tmux-sessionizer
tmux_sessionizer="$scripts_folder/tmux-sessionizer"
if [[ -f "$tmux_sessionizer" ]]; then
  mv "$tmux_sessionizer" "$backup_folder"
fi
cp "$PWD/tmux-sessionizer" "$tmux_sessionizer"

chmod u+x tmux-session-list
tmux_session_list="$scripts_folder/tmux-session-list"
if [[ -f "$tmux_session_list" ]]; then
  mv "$tmux_session_list" "$backup_folder"
fi
cp "$PWD/tmux-session-list" "$tmux_session_list"

ideavimrc="$HOME/.ideavimrc"
if [[ -f "$ideavimrc" ]]; then
  mv "$ideavimrc" "$backup_folder"
fi
cp "$PWD/ideavimrc" "$ideavimrc"
