# Set red pane color to distinguish linux/container from macos
# Foreground color of a pane is the actual dashed line that makes up the border
# Background color is by default black
set -w -g pane-active-border-style fg=red,bright,bg=default
